events {
    worker_connections 1024;
}

http {
    upstream bff-user {
        server bff-user:3000;
    }
    server {
        listen 80;
        server_name bff-user.development.mairie360.fr;

        location / {
            proxy_pass http://bff-user;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            send_timeout 60s;
        }
    }
}
