import axios from 'axios';
import type { AxiosRequestConfig } from 'axios';
import { getCoreAPIMairie360 } from '@mairie360/core-api-openapi/endpoints/coreAPIMairie360';
import type { LoginResponseView } from '@mairie360/core-api-openapi/model';

/**
 * Axios instance shared by every operation generated by orval. It carries no base URL: Core API's URL is
 * read from `CORE_API_URL` (+ optional `CORE_API_PORT`) by `baseUrl('CORE_API')` of `@mairie360/bffs-lib`
 * on every call and passed in the options of that call (503 when it is missing, never a `localhost`
 * default), so nothing is frozen at import time.
 */
export const coreClient = axios.create({
    timeout: 5000,
    headers: {
        'Content-Type': 'application/json',
    },
});

// No default token: every call forwards only the caller's session, and Core's public routes
// (/api/v1/auth/*) stay anonymous. Outgoing URLs are not logged (they carry user and group ids).

/** Client generated from the Core API OpenAPI contract. */
export const coreApi = getCoreAPIMairie360(coreClient);

/**
 * Core API's paginated lists (>= 2.0.0) take `limit` (1 to 500, 100 by default) and `offset` (0 to 1000000).
 * The list routes forward the page the front asks for; internal membership checks read the largest page.
 */
export const CORE_MAX_LIMIT = 500;
export const CORE_MAX_OFFSET = 1_000_000;
export const CORE_LARGEST_PAGE = { limit: CORE_MAX_LIMIT } as const;

/** Body of Core's `POST /api/v1/auth/keycloak` (`KeycloakLoginView`). */
export interface KeycloakLoginView {
    code: string;
    redirect_uri: string;
    code_verifier?: string | null;
    nonce?: string | null;
    device_info: string;
}

/**
 * Keycloak single sign-on: Core redeems the authorization code and answers like `POST /api/v1/auth/login`.
 * Still hand-written: `@mairie360/core-api-openapi` >= 2.0.0 ships `coreApi.keycloakLogin`, the switch is
 * left for a later change.
 */
export const keycloakLogin = (keycloakLoginView: KeycloakLoginView, options?: AxiosRequestConfig) => (
    coreClient.post<LoginResponseView>('/api/v1/auth/keycloak', keycloakLoginView, options)
);

// --- Passkeys (MAIR-505), hand-written like the Keycloak sign-in: `@mairie360/core-api-openapi` 2.0.0
// predates them. Switch to the generated functions once a Core contract with them is published, and add
// them to `upstream-contracts.test.ts` at the same time.

/** WebAuthn JSON (options of a ceremony, `PublicKeyCredential.toJSON()`): relayed as is, Core checks it. */
export type WebAuthnJson = Record<string, unknown>;

/** Body of Core's `POST /api/v1/auth/passkey` (`PasskeyLoginView`). */
export interface PasskeyLoginView {
    challenge_id: string;
    credential: WebAuthnJson;
    device_info: string;
}

/** Answer of Core's `POST /api/v1/auth/passkey/options` and `POST /api/v1/user/me/passkeys/options`. */
export interface PasskeyCeremonyOptionsView {
    challenge_id: string;
    public_key: WebAuthnJson;
}

/** Body of Core's `POST /api/v1/user/me/passkeys/` (`RegisterPasskeyView`). */
export interface RegisterPasskeyView {
    challenge_id: string;
    label: string;
    credential: WebAuthnJson;
}

/** A registered passkey as Core lists it (`PasskeySummary`): never the public key. */
export interface PasskeySummaryView {
    id: number;
    label: string;
    created_at: string;
    last_used_at: string | null;
}

/** Answer of Core's `GET /api/v1/user/me/passkeys/` (`PasskeyListResponseView`). */
export interface PasskeyListView {
    passkeys: PasskeySummaryView[];
}

/** Opens a discoverable passkey sign-in: public on Core API, no body. */
export const passkeyLoginOptions = (options?: AxiosRequestConfig) => (
    coreClient.post<PasskeyCeremonyOptionsView>('/api/v1/auth/passkey/options', undefined, options)
);

/** Completes a passkey sign-in: Core answers like `POST /api/v1/auth/login`. */
export const passkeyLogin = (passkeyLoginView: PasskeyLoginView, options?: AxiosRequestConfig) => (
    coreClient.post<LoginResponseView>('/api/v1/auth/passkey', passkeyLoginView, options)
);

/** Opens the registration of a passkey for the caller's account. */
export const passkeyRegistrationOptions = (options?: AxiosRequestConfig) => (
    coreClient.post<PasskeyCeremonyOptionsView>('/api/v1/user/me/passkeys/options', undefined, options)
);

/** Registers the passkey answering a registration ceremony (Core answers 201). */
export const registerPasskey = (registerPasskeyView: RegisterPasskeyView, options?: AxiosRequestConfig) => (
    coreClient.post<PasskeySummaryView>('/api/v1/user/me/passkeys/', registerPasskeyView, options)
);

/** The passkeys of the caller's account. */
export const listPasskeys = (options?: AxiosRequestConfig) => (
    coreClient.get<PasskeyListView>('/api/v1/user/me/passkeys/', options)
);

/** Deletes one passkey of the caller's account (Core answers 204, or 404 for someone else's). */
export const deletePasskey = (passkeyId: number, options?: AxiosRequestConfig) => (
    coreClient.delete<void>(`/api/v1/user/me/passkeys/${passkeyId}/`, options)
);

// The groups below keep the interface the BFF routes consume, on top of the single generated client
// `getCoreAPIMairie360`.
export const coreAuthClient = {
    login: coreApi.login,
    keycloakLogin,
    passkeyLoginOptions,
    passkeyLogin,
    forceChangePassword: coreApi.forceChangePassword,
    forgotPassword: coreApi.forgotPassword,
    resetPassword: coreApi.resetPassword,
};

export const coreAdminUsersClient = {
    adminListUsers: coreApi.adminListUsers,
    adminGetUser: coreApi.adminGetUser,
    adminPostUser: coreApi.adminPostUser,
    adminPatchUser: coreApi.adminPatchUser,
    adminDeleteUser: coreApi.adminDeleteUser,
    adminResetUserPassword: coreApi.adminResetUserPassword,
    adminAddRoleToUser: coreApi.adminAddRoleToUser,
    adminDeleteUserRole: coreApi.adminDeleteUserRole,
};

export const coreAdminRolesClient = {
    adminGetRole: coreApi.adminGetRole,
    adminPostRole: coreApi.adminPostRole,
    adminPutRole: coreApi.adminPutRole,
    adminDeleteRole: coreApi.adminDeleteRole,
    adminPatchRole: coreApi.adminPatchRole,
};

export const coreUsersClient = {
    getMe: coreApi.getMe,
    patchMe: coreApi.patchMe,
    getUser: coreApi.getUser,
    passkeyRegistrationOptions,
    registerPasskey,
    listPasskeys,
    deletePasskey,
};

export const coreGroupsClient = {
    getGroups: coreApi.getGroups,
    postGroup: coreApi.postGroup,
    getGroup: coreApi.getGroup,
    deleteGroup: coreApi.deleteGroup,
    patchGroup: coreApi.patchGroup,
    // Historical name kept for the BFF routes.
    getGroupUsers: coreApi.getGroupMembers,
    addUserToGroup: coreApi.addUserToGroup,
    removeUserFromGroup: coreApi.removeUserFromGroup,
};

export const coreSessionsClient = {
    getActiveSessions: coreApi.getActiveSessions,
    history: coreApi.history,
    logout: coreApi.logout,
    refresh: coreApi.refresh,
    revoke: coreApi.revoke,
};

export default coreApi;
