import axios from 'axios';
import { getCoreAPIMairie360 } from '@mairie360/core-api-openapi/endpoints/coreAPIMairie360';

/**
 * Axios instance shared by every operation generated by orval. It carries no base URL: Core API's URL is
 * read from `CORE_API_URL` (+ optional `CORE_API_PORT`) by `baseUrl('CORE_API')` of `@mairie360/bffs-lib`
 * on every call and passed in the options of that call (503 when it is missing, never a `localhost`
 * default), so nothing is frozen at import time.
 */
export const coreClient = axios.create({
    timeout: 5000,
    headers: {
        'Content-Type': 'application/json',
    },
});

// No default token: every call forwards only the caller's session, and Core's public routes
// (/api/v1/auth/*) stay anonymous. Outgoing URLs are not logged (they carry user and group ids).

/** Client generated from the Core API OpenAPI contract. */
export const coreApi = getCoreAPIMairie360(coreClient);

/**
 * Largest page Core API (>= 2.0.0) serves on its paginated lists (`limit`, 100 by default). The BFF routes
 * that expose a whole list (groups, group members, session history) ask for this page size.
 */
export const CORE_MAX_PAGE = { limit: 500 } as const;

// The groups below keep the interface the BFF routes consume, on top of the single generated client
// `getCoreAPIMairie360`.
export const coreAuthClient = {
    login: coreApi.login,
    keycloakLogin: coreApi.keycloakLogin,
    forceChangePassword: coreApi.forceChangePassword,
    forgotPassword: coreApi.forgotPassword,
    resetPassword: coreApi.resetPassword,
};

export const coreAdminUsersClient = {
    adminListUsers: coreApi.adminListUsers,
    adminGetUser: coreApi.adminGetUser,
    adminPostUser: coreApi.adminPostUser,
    adminPatchUser: coreApi.adminPatchUser,
    adminDeleteUser: coreApi.adminDeleteUser,
    adminResetUserPassword: coreApi.adminResetUserPassword,
    adminAddRoleToUser: coreApi.adminAddRoleToUser,
    adminDeleteUserRole: coreApi.adminDeleteUserRole,
};

export const coreAdminRolesClient = {
    adminGetRole: coreApi.adminGetRole,
    adminPostRole: coreApi.adminPostRole,
    adminPutRole: coreApi.adminPutRole,
    adminDeleteRole: coreApi.adminDeleteRole,
    adminPatchRole: coreApi.adminPatchRole,
};

export const coreUsersClient = {
    getMe: coreApi.getMe,
    patchMe: coreApi.patchMe,
    getUser: coreApi.getUser,
};

export const coreGroupsClient = {
    getGroups: coreApi.getGroups,
    postGroup: coreApi.postGroup,
    getGroup: coreApi.getGroup,
    deleteGroup: coreApi.deleteGroup,
    patchGroup: coreApi.patchGroup,
    // Historical name kept for the BFF routes.
    getGroupUsers: coreApi.getGroupMembers,
    addUserToGroup: coreApi.addUserToGroup,
    removeUserFromGroup: coreApi.removeUserFromGroup,
};

export const coreSessionsClient = {
    getActiveSessions: coreApi.getActiveSessions,
    history: coreApi.history,
    refresh: coreApi.refresh,
    revoke: coreApi.revoke,
};

export default coreApi;
