name: Auto Approve Renovate
on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    # On ne l'exécute que si c'est le bot Renovate qui a ouvert la PR
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}