name: BFF User CICD

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  CICD:
    uses: mairie360/CICD/.github/workflows/BFFs-cicd.yml@v1.2.1
    with:
      package_name: bff-user
      node_version: 20
    secrets: inherit