name: BFF User CICD

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  CICD:
    uses: mairie360/CICD/.github/workflows/BFFs-cicd.yml@v1.7.5
    with:
      package_name: bff-user
      cicd_version: v1.7.5
      node_version: 20
    secrets: inherit
